#spring:
#  cloud:
#    gateway:
#      discovery:
#        locator:
#          enabled: true
#      routes:
#      - id: live-api
#        uri: lb://live-api
#        predicates:
#        - Path=/live/api/**
#          