#spring:
#  application:
#    name: live-im-core-server
#  data:
#    redis:
#      port: 6379
#      host: 127.0.0.1
#      password: 123456
#      lettuce:
#        pool:
#          min-idle: 10
#          max-active: 100
#          max-idle: 10
#
#im:
#  port: 8085

#rmq:
#  producer:
#    nameSrv: localhost:9876
#    groupName: ${spring.application.name}
#    applicationName: ${spring.application.name}
#    sendMsgTimeout: 3000
#    retryTimes: 2

#  
#dubbo:
#  application:
#    name: ${spring.application.name}
#  registry:
#    address: nacos://127.0.0.1:8848?namespace=live-test&&username=nacos&&password=nacos
#  protocol:
#    name: dubbo
#    port: 9091
#    threadpool: fixed
#    dispatcher: execution
#    threads: 500
#    accepts: 500