version: "3"
services:
  live-user-provider-docker-1:
    container_name: live-user-provider-docker-1
    image: "registry.baidubce.com/live-test/live-user-provider-docker:1.0.5"
    ports:
      - "9091:9091"
    volumes:
      - /tmp/logs/live-user-provider:/tmp/logs/live-user-provider
    environment:
      - TZ=America/Toronto
      - DUBBO_IP_TO_REGISTRY=192.168.1.7
      - DUBBO_PORT_TO_REGISTRY=9091
      - DUBBO_PORT_TO_BIND=9091
      - JAVA_OPTS=-XX:MetaspaceSize=128m -XX:MaxMetaspaceSize=128m -Xms512m -Xmx512m -Xmn128m -Xss256k
    extra_hosts:
      - "nacos.com:192.168.1.7"
      - "cloud.db:192.168.1.7"
      - "rmq.com:192.168.1.7"

  live-user-provider-docker-2:
    container_name: live-user-provider-docker-2
    image: "registry.baidubce.com/live-test/live-user-provider-docker:1.0.5"
    ports:
      - "9092:9092"
    volumes:
      - /tmp/logs/live-user-provider:/tmp/logs/live-user-provider
    environment:
      - TZ=America/Toronto
      - DUBBO_IP_TO_REGISTRY=192.168.1.7
      - DUBBO_PORT_TO_REGISTRY=9092
      - DUBBO_PORT_TO_BIND=9092
      - JAVA_OPTS=-XX:MetaspaceSize=128m -XX:MaxMetaspaceSize=128m -Xms512m -Xmx512m -Xmn128m -Xss256k
    extra_hosts:
      - "nacos.com:192.168.1.7"
      - "cloud.db:192.168.1.7"
      - "rmq.com:192.168.1.7"
