version: "3.8"

volumes:
  mysqldata:
    driver: local

services:
  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: live_commerce
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - "mysqldata:/var/lib/mysql"
      - "./my.cnf:/etc/mysql/conf.d/my.cnf"
    ports:
      - 3306:3306
