#spring:
#  application:
#    name: live-msg-provider
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    #MySQL master addr (we're not using sharding yet')
#    url: jdbc:mysql://localhost:8808/live_msg?useUnicode=true&characterEncoding=utf8
#    username: root
#    password: root
#    hikari:
#      pool-name: user-pool
#      minimum-idle: 10
#      idle-timeout: 60000
#      maximum-pool-size: 200
#      #connection-init-sql: select 1
#      connection-timeout: 4000
#      max-lifetime: 60000
#  data:
#    redis:
#      port: 6379
#      host: 127.0.0.1
#      password: 123456
#      lettuce:
#        pool:
#          min-idle: 10
#          max-active: 100
#          max-idle: 10
#          
##rocketmq
#rmq:
#  producer:
#    nameSrv: 127.0.0.1:9876
#    groupName: ${spring.application.name}
#    retryTimes: 3
#    sendTimeOut: 3000
#  consumer:
#    nameSrv: 127.0.0.1:9876
#    groupName: ${spring.application.name}
#      
#dubbo:
#  application:
#    name: ${spring.application.name}
#  registry:
#    address: nacos://127.0.0.1:8848?namespace=live-test&&username=nacos&&password=nacos
#  protocol:
#    name: dubbo
#    port: 9091
#    threadpool: fixed
#    dispatcher: execution
#    threads: 500
#    accepts: 500
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
